apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: geo-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: geo-server
  template:
    metadata:
      labels:
        role: geo-server
    spec:
      containers:
      - name: geo-server
        image: kartoza/geoserver
        ports:
          - name: geoserver
            containerPort: 8080
        securityContext:
          privileged: true

